# Redirect for end-userâ€™s browser preference override
[[redirects]]
  from = "/*"
  to = "/es/:splat"
  status = 302
  conditions = {Language = ["es"]}  

# Default
[[redirects]]
  from = "/*"
  to = "/en/:splat"
  status = 200

